### ISSUE TITLE
Изучить redux

### ISSUE THREAD

**Issue by N1kk1337** [N1kk1337/rs-clone#1]
Давайте покидаем сюда видео и туториалы.

**Comment by N1kk1337** [comment]
https://www.youtube.com/watch?v=5Qtqzeh5FeM&list=PL6DxKON1uLOHsBCJ_vVuvRsW84VnqmPp6
Мне нравятся его туториалы. Оно там каплю деприкейтед судя по тому что я попробовал, но на самом деле всё работает.

**Comment by Baxromxoja16** [comment]
https://www.youtube.com/watch?v=YdYyYMFPa44  объясняется в corejs
